# Uncomment this line to define a global platform for your project
 platform :tvos, '9.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'BancoSantanderShareholder-tvOS' do

	pod 'Alamofire', '~> 3.2.0'
    pod 'SWXMLHash'
    pod 'HCYoutubeParser'
    pod 'SDWebImage'

end

